Map<String, String> bookMapping = {
  'MAT': 'Matthew',
  'MRK': 'Mark',
  'LUK': 'Luke',
  'JHN': 'John',
  'JHN_TEST': 'John (test)',
  'ACT': 'Acts',
  'ROM': 'Romans',
  'CO1': '1 Corinthians',
  'CO2': '2 Corinthians',
  'GAL': 'Galatians',
  'EPH': 'Ephesians',
  'PHP': 'Philippians',
  'COL': 'Colossians',
  'TH1': '1 Thessalonians',
  'TH2': '2 Thessalonians',
  'TI1': '1 Timothy',
  'TI2': '2 Timothy',
  'TIT': 'Titus',
  'PHM': 'Philemon',
  'HEB': 'Hebrews',
  'JAM': 'James',
  'PE1': '1 Peter',
  'PE2': '2 Peter',
  'JN1': '1 John',
  'JN2': '2 John',
  'JN3': '3 John',
  'JDE': 'Jude',
  'REV': 'Revelation',
};
